# Generated by Django 3.2.9 on 2021-12-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211220_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=0),
        ),
    ]
